import { project as rawProject, rotate, vec } from "./math3d.js";
const QUBITS=["A","B","C"],DEG=Math.PI/180,QUBIT_COLORS=["#d9a900","#ef233c","#9b4f00"],FILTER_SCALE=92/125,filterCamera={yaw:25*Math.PI/180,pitch:-8*Math.PI/180};
function project(v,cx,cy,r){return rawProject(v,cx,cy,r*FILTER_SCALE,filterCamera.yaw,filterCamera.pitch)}
function cmul(a,b){return{re:a.re*b.re-a.im*b.im,im:a.re*b.im+a.im*b.re}}
function overlap(theta,phi,out,input){const h=theta*DEG/2,c=Math.cos(h),s=Math.sin(h),p=phi*DEG;if(!out)return input?{re:s*Math.cos(p),im:-s*Math.sin(p)}:{re:c,im:0};return input?{re:c*Math.cos(p),im:-c*Math.sin(p)}:{re:-s,im:0}}
export function measurementProbabilities(state,filters){return Array.from({length:8},(_,out)=>{let total={re:0,im:0};for(let input=0;input<8;input++){let factor={re:state[input],im:0};for(let q=0;q<3;q++)factor=cmul(factor,overlap(filters[q].theta,filters[q].phi,(out>>(2-q))&1,(input>>(2-q))&1));total.re+=factor.re;total.im+=factor.im}return total.re**2+total.im**2})}
export function sampleDistribution(probabilities,shots,random=Math.random){const counts=Array(8).fill(0);for(let shot=0;shot<shots;shot++){const r=random();let sum=0,index=7;for(let i=0;i<8;i++){sum+=probabilities[i];if(r<sum){index=i;break}}counts[index]++}return counts}
export function filterDirection({theta,phi}){let direction;if(theta===0)direction="北 |0⟩";else if(theta===180)direction="南 |1⟩";else if(theta===90&&phi===0)direction="東 |+⟩";else if(theta===90&&phi===90)direction="表 |+i⟩";else if(theta===90&&phi===180)direction="西 |−⟩";else if(theta===90&&phi===270)direction="裏 |−i⟩";else direction=`表裏軸 ${theta}° → 南北軸 ${phi}°`;return `フィルター方向：${direction}`}
export function outcomeLabel(index){return QUBITS.map((name,q)=>`${name}:${((index>>(2-q))&1)?"× 通らない":"○ 通る"}`).join(" / ")}
function filterVector(f){const t=f.theta*DEG,p=f.phi*DEG;return vec(Math.sin(t)*Math.cos(p),Math.sin(t)*Math.sin(p),Math.cos(t))}
function stateVector(state,q){const mask=[4,2,1][q];let x=0,z=0,p0=0,p1=0;for(let i=0;i<8;i++)if(!(i&mask)){const a=state[i],b=state[i|mask];x+=2*a*b;p0+=a*a;p1+=b*b}z=p0-p1;return vec(x,0,z)}
function arrow(cx,cy,tip,color,width){const white=color==="#ffffff",a=Math.atan2(tip.y-cy,tip.x-cx),ball=white?5.5:8,head=white?15:22,vx=tip.x-ball*Math.cos(a),vy=tip.y-ball*Math.sin(a),base=white?10:15,bx=vx-base*Math.cos(a),by=vy-base*Math.sin(a);return `<line x1="${cx}" y1="${cy}" x2="${bx}" y2="${by}" stroke="${color}" stroke-width="${white?2.5:width}" stroke-linecap="round"/><polygon points="${vx},${vy} ${vx-head*Math.cos(a-.5)},${vy-head*Math.sin(a-.5)} ${vx-head*Math.cos(a+.5)},${vy-head*Math.sin(a+.5)}" fill="${color}"/>`}
function drawAxes(){const svg=document.getElementById("filter-view"),yaw=25*DEG,pitch=-8*DEG,r=125;let html="";for(let q=0;q<3;q++){const cx=180+q*360,cy=190;for(const [axis,color] of [[vec(0,0,1),"#687b8c"],[vec(1,0,0),"#8a7560"],[vec(0,1,0),"#708274"]]){const a=project(axis,cx,cy,r*1.22,yaw,pitch),b=project(vec(-axis.x,-axis.y,-axis.z),cx,cy,r*1.22,yaw,pitch);html+=`<line x1="${b.x}" y1="${b.y}" x2="${a.x}" y2="${a.y}" stroke="${color}" stroke-width="1.6" opacity=".68"/>`}}svg.insertAdjacentHTML("afterbegin",html)}
function drawDirections(){const svg=document.getElementById("filter-view"),r=125,directions=[["北 |0⟩",vec(0,0,1),"#2a78d6","南北軸","#687b8c"],["南 |1⟩",vec(0,0,-1),"#d1495b"],["東 |+⟩",vec(1,0,0),"#1baf7a","東西軸","#8a7560"],["西 |−⟩",vec(-1,0,0),"#c98500"],["表 |+i⟩",vec(0,1,0),"#d43791","表裏軸","#708274"],["裏 |−i⟩",vec(0,-1,0),"#008ca8"]];let html="";for(let q=0;q<3;q++){const cx=180+q*360,cy=190;for(const [label,v,color,axisName,axisColor] of directions){const edge=project(v,cx,cy,r),far=project(v,cx,cy,r*1.55);html+=`<circle cx="${edge.x}" cy="${edge.y}" r="3.5" fill="${color}"/><text x="${far.x}" y="${far.y+(axisName?0:5)}" text-anchor="middle" font-size="13" font-weight="800" fill="${color}"><tspan x="${far.x}" dy="0">${label}</tspan>${axisName?`<tspan x="${far.x}" dy="14" font-size="10.5" font-weight="700" fill="${axisColor}">${axisName}</tspan>`:""}</text>`}}svg.insertAdjacentHTML("beforeend",html)}
function recolorFilter(){const svg=document.getElementById("filter-view");svg.querySelectorAll('[stroke="#ef2f91"]').forEach(x=>x.setAttribute("stroke","#f04b23"));svg.querySelectorAll('[fill="#ef2f91"],[fill="#d43791"]').forEach(x=>x.setAttribute("fill","#f04b23"))}
function recolorAxes(){const svg=document.getElementById("filter-view"),colors={"#687b8c":"#4f708f","#8a7560":"#98703d","#708274":"#795f82"};for(const [oldColor,newColor] of Object.entries(colors)){svg.querySelectorAll(`[stroke="${oldColor}"]`).forEach(x=>x.setAttribute("stroke",newColor));svg.querySelectorAll(`[fill="${oldColor}"]`).forEach(x=>x.setAttribute("fill",newColor))}}
function compactGlobes(){const svg=document.getElementById("filter-view");svg.querySelectorAll('circle[r="125"]').forEach(x=>x.setAttribute("r","92"));svg.querySelectorAll('ellipse[rx="125"]').forEach(x=>{x.setAttribute("rx","92");x.setAttribute("ry",String(+x.getAttribute("ry")*FILTER_SCALE))});svg.querySelectorAll('ellipse[ry="125"]').forEach(x=>{x.setAttribute("rx",String(+x.getAttribute("rx")*FILTER_SCALE));x.setAttribute("ry","92")});svg.querySelectorAll('line[stroke="#2a78d6"][opacity=".42"]').forEach(x=>x.remove())}
function styleQubitLabels(){const svg=document.getElementById("filter-view");QUBITS.forEach((name,q)=>{const label=[...svg.querySelectorAll("text")].find(x=>x.textContent===name);if(!label)return;label.setAttribute("x",String(48+q*360));label.setAttribute("y","48");label.setAttribute("fill",QUBIT_COLORS[q]);label.setAttribute("font-size","24")})}
function finishArrowLayering(){const svg=document.getElementById("filter-view");svg.querySelectorAll('circle[fill="#ef2f91"],circle[fill="#f04b23"]').forEach(ball=>{ball.setAttribute("stroke","none");ball.setAttribute("r","8")});const stateParts=[...svg.querySelectorAll('line[stroke="#ffffff"],polygon[fill="#ffffff"],circle[fill="#fff"][stroke="#52606d"]')];stateParts.forEach(part=>{if(part.tagName.toLowerCase()==="circle"){part.setAttribute("stroke","none");part.setAttribute("r","5.5")}svg.append(part)})}
function orbitPoints(start,axis,angle,cx,cy,r,steps=90){const points=[];for(let i=0;i<=steps;i++){const p=project(rotate(start,axis,angle*i/steps),cx,cy,r);points.push(`${p.x.toFixed(1)},${p.y.toFixed(1)}`)}return points.join(" ")}
function drawFilterPaths(filters){const svg=document.getElementById("filter-view"),r=125;let html="";filters.forEach((filter,q)=>{const cx=180+q*360,cy=190,north=vec(0,0,1),afterFirst=rotate(north,vec(0,1,0),filter.theta*DEG);html+=`<polyline points="${orbitPoints(north,vec(0,1,0),Math.PI*2,cx,cy,r)}" fill="none" stroke="#5f6d78" stroke-width="1.2" stroke-dasharray="4,6" opacity=".38"/>`;if(filter.theta>0)html+=`<polyline points="${orbitPoints(north,vec(0,1,0),filter.theta*DEG,cx,cy,r,45)}" fill="none" stroke="#f04b23" stroke-width="1.8" stroke-dasharray="5,4" opacity=".78"/>`;if(filter.theta>0&&filter.theta<180){html+=`<polyline points="${orbitPoints(afterFirst,vec(0,0,1),Math.PI*2,cx,cy,r)}" fill="none" stroke="#788690" stroke-width="1.2" stroke-dasharray="2,6" opacity=".42"/>`;if(filter.phi>0)html+=`<polyline points="${orbitPoints(afterFirst,vec(0,0,1),filter.phi*DEG,cx,cy,r,60)}" fill="none" stroke="#f04b23" stroke-width="1.8" stroke-dasharray="5,4" opacity=".78"/>`}});svg.insertAdjacentHTML("afterbegin",html)}
function drawSpheres(state,filters){const svg=document.getElementById("filter-view"),yaw=25*DEG,pitch=-8*DEG,r=125;let html=`<defs><radialGradient id="filter-globe" cx="35%" cy="28%"><stop offset="0" stop-color="#fff" stop-opacity=".38"/><stop offset="1" stop-color="#7890a5" stop-opacity=".12"/></radialGradient></defs>`;for(let q=0;q<3;q++){const cx=180+q*360,cy=190;html+=`<circle cx="${cx}" cy="${cy}" r="${r}" fill="url(#filter-globe)" stroke="#7890a5" stroke-width="1.2"/><ellipse cx="${cx}" cy="${cy}" rx="${r}" ry="${r*.34}" fill="none" stroke="#6e9db9" opacity=".28"/><ellipse cx="${cx}" cy="${cy}" rx="${r*.35}" ry="${r}" fill="none" stroke="#ba8b58" opacity=".25"/><line x1="${cx}" y1="${cy-r-15}" x2="${cx}" y2="${cy+r+15}" stroke="#2a78d6" opacity=".42"/><text x="${cx}" y="28" text-anchor="middle" font-size="22" font-weight="800">${QUBITS[q]}</text><text x="${cx}" y="365" text-anchor="middle" font-size="13" fill="#d43791">${filterDirection(filters[q])}</text>`;const s=project(stateVector(state,q),cx,cy,r,yaw,pitch),f=project(filterVector(filters[q]),cx,cy,r,yaw,pitch);html+=arrow(cx,cy,s,"#ffffff",5)+`<circle cx="${s.x}" cy="${s.y}" r="7" fill="#fff" stroke="#52606d"/>`+arrow(cx,cy,f,"#ef2f91",5)+`<circle cx="${f.x}" cy="${f.y}" r="8" fill="#ef2f91" stroke="#fff" stroke-width="2"/>`}svg.innerHTML=html}
export function initMeasurement({onFilters}){const holder=document.getElementById("measurement-bases"),exact=document.getElementById("measurement-exact"),samples=document.getElementById("measurement-samples");let state=[1,0,0,0,0,0,0,0],filters=QUBITS.map(()=>({theta:0,phi:0}));
  holder.innerHTML=QUBITS.map((name,q)=>`<div class="filter-controls"><strong>${name}のフィルター</strong><label class="axis-control front-back-axis">① 表裏軸回転<input type="range" data-q="${q}" data-kind="theta" min="0" max="180" step="5" value="0"><output>0°</output></label><label class="axis-control north-south-axis">② 南北軸回転<input type="range" data-q="${q}" data-kind="phi" min="0" max="360" step="5" value="0"><output>0°</output></label></div>`).join("");
  const row=(value,i,right)=>`<div class="state-row measurement-row"><code>${i.toString(2).padStart(3,"0")}</code><span><i style="width:${value*100}%"></i></span><b>${right}</b></div>`;function render(){const p=measurementProbabilities(state,filters);exact.innerHTML=p.map((v,i)=>row(v,i,`${(v*100).toFixed(1)}%`)).join("");drawSpheres(state,filters);recolorFilter();compactGlobes();drawAxes();drawFilterPaths(filters);drawDirections();recolorAxes();styleQubitLabels();finishArrowLayering();return p}
  holder.oninput=e=>{if(!e.target.matches("input"))return;const q=+e.target.dataset.q,kind=e.target.dataset.kind;filters[q]={...filters[q],[kind]:+e.target.value};e.target.nextElementSibling.textContent=`${e.target.value}°`;samples.className="sample-empty";samples.textContent="フィルター方向が変わりました。もう一度測定してください。";render();onFilters?.(filters.map(f=>({...f})))};
  const filterSvg=document.getElementById("filter-view");let drag=null;
  filterSvg.addEventListener("pointerdown",e=>{drag={x:e.clientX,y:e.clientY,yaw:filterCamera.yaw,pitch:filterCamera.pitch};filterSvg.setPointerCapture(e.pointerId);filterSvg.classList.add("dragging")});
  filterSvg.addEventListener("pointermove",e=>{if(!drag)return;filterCamera.yaw=drag.yaw+(e.clientX-drag.x)*.008;filterCamera.pitch=drag.pitch-(e.clientY-drag.y)*.008;render()});
  const endDrag=()=>{drag=null;filterSvg.classList.remove("dragging")};filterSvg.addEventListener("pointerup",endDrag);filterSvg.addEventListener("pointercancel",endDrag);
  document.getElementById("filter-reset-view").onclick=()=>{filterCamera.yaw=25*DEG;filterCamera.pitch=-8*DEG;render()};
  function measure(shots){const counts=sampleDistribution(render(),shots);document.getElementById("measurement-sample-title").textContent=`測定結果（${shots}回）`;samples.className="";samples.innerHTML=counts.map((count,i)=>row(count/shots,i,`${count}回`)).join("")}document.getElementById("measure-once").onclick=()=>measure(1);document.getElementById("measure-many").onclick=()=>measure(1000);render();onFilters?.(filters);return{update(next){state=[...next];render()}}}
